apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
  namespace: sonarqube-ns
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31000
      name: sonarport
  selector:
    name: sonar
