apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: sonarqube-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonar
  template:
    metadata:
      name: sonar
      labels:
        name: sonar
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
        - image: sonarqube:9.4.0-community
          imagePullPolicy: IfNotPresent
          name: sonar
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_USERNAME
              value: sonar
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
              name: sonar