apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins-ns
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins