apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  namespace: nexus-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3:latest
        env:
          - name: MAX_HEAP
            value: "800m"
          - name: MIN_HEAP
            value: "300m"
        ports:
          - containerPort: 8081
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
      volumes:
        - name: nexus-data
          hostPath:
            path: /run/desktop/mnt/host/c/data_nexus
            type: Directory
        